FROM python:3.11-slim-bookworm

WORKDIR /app

COPY ../data-ingestion/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ../data-crawling /app

CMD ["python3", "src/storing.py"]